/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef BRICK_BREAKER_PRIVATE_H
#define BRICK_BREAKER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.249"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	249
#define COMPANY_NAME	""
#define FILE_VERSION	"1.0.0.249"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Brick Breaker"
#define PRODUCT_NAME	"BrickBreaker"
#define PRODUCT_VERSION	"1.0.0.249"

#endif /*BRICK_BREAKER_PRIVATE_H*/
